plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Experimental Logic
description: Logic is an experimental science based on non-monotonic evolution of interactions/games.
